### Titanic Notebook

Data comes from the [kaggle](https://www.kaggle.com/competitions/titanic/) challenge to predict survival on the titanic.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# training data
df = pd.read_csv('train.csv')
# test data for submission without outcome
df_test = pd.read_csv('test.csv')
assert df.shape[1] == df_test.shape[1] + 1
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
assert df_test.shape[0] == 418 # hence submission file will have 418 rows with 2 columns (ID + outcome)
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

#### Data description


9 independent variables to predict survival + passenger id and name:


| Column    | Description                              | Values                                |
|-----------|------------------------------------------|---------------------------------------|
| survival  | Survival                                 | 0 = No, 1 = Yes                       |
| pclass    | Ticket class                             | 1 = 1st, 2 = 2nd, 3 = 3rd             |
| sex       | Sex                                      |                                       |
| Age       | Age in years                             |                                       |
| sibsp     | # of siblings / spouses aboard the Titanic |                                       |
| parch     | # of parents / children aboard the Titanic |                                       |
| ticket    | Ticket number                            |                                       |
| fare      | Passenger fare                           |                                       |
| cabin     | Cabin number                             |                                       |
| embarked  | Port of Embarkation                      | C = Cherbourg, Q = Queenstown, S = Southampton |


For *embarked* and *ticket* are likely independent of the outcome, they will be dropped. We also drop the name as *Age* and *sex* accounts for social factors such as being a child or being female ('Women and children first!').

Lastly, *passangerid* is assumed to be irrelevant, too.

In [4]:
df.drop(columns=['Embarked', 'Name', 'Ticket', 'PassengerId'], inplace=True)
df['Sex'] = df['Sex'].apply(lambda x: 1.0 if x == 'male' else 0.0)
print(df.isna().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
dtype: int64

In [23]:
687 / df.shape[0] # 0.7710437710437711 missing values in Cabin --> drop column
177 / df.shape[0] # 0.19865319865319866 missing values in Age --> handle missing values by filling them with the median

0.19865319865319866

In [5]:
df = df.drop(columns=['Cabin'])
df['Age'] = df['Age'].fillna(df['Age'].median())
assert df.isna().sum().all() == 0
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0         0       3  1.0  22.0      1      0   7.2500
1         1       1  0.0  38.0      1      0  71.2833
2         1       3  0.0  26.0      0      0   7.9250
3         1       1  0.0  35.0      1      0  53.1000
4         0       3  1.0  35.0      0      0   8.0500

In [ ]:
# apply same preprocessing to test data
df_test['Age'] = df['Age'].fillna(df['Age'].median())
df_test = df_test.drop(columns=['Embarked', 'Name', 'Ticket', 'PassengerId', 'Cabin'])
df_test['Sex'] = df_test['Sex'].apply(lambda x: 1.0 if x == 'male' else 0.0)

In [20]:
# hold 0.10% back for validation
from sklearn.model_selection import train_test_split

df_training, df_validation = train_test_split(df, test_size=0.10, random_state=42)
df_training_y, df_validation_y = df_training['Survived'], df_validation['Survived']

df_training.drop(columns=['Survived'], inplace=True)
df_validation.drop(columns=['Survived'], inplace=True)

#### Ensemble models

In [7]:
# train a model
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score


model = GradientBoostingClassifier(n_estimators=100, random_state=42)
model.fit(df_training, df_training_y)
preds = model.predict(df_validation)
gbm_accuracy_score = accuracy_score(df_validation_y, preds)


model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(df_training, df_training_y)
preds = model.predict(df_validation)
rfr_accuracy_score = accuracy_score(df_validation_y, preds)

print(gbm_accuracy_score, rfr_accuracy_score)

0.8333333333333334 0.8222222222222222

In [ ]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

# Define parameter grids
gbm_param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5],
    'subsample': [0.5, 0.75, 1.0],
    'min_samples_leaf': [1, 2, 3]
}

rfr_param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10], 
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_leaf_nodes': [None, 5, 10, 20],
    'class_weight': ['balanced', 'balanced_subsample', None]
    
}

# Grid search for GradientBoostingClassifier
gbm_grid_search = GridSearchCV(GradientBoostingClassifier(random_state=42), gbm_param_grid, cv=5, scoring='accuracy')
gbm_grid_search.fit(df_training, df_training_y)
gbm_best_model = gbm_grid_search.best_estimator_
gbm_preds = gbm_best_model.predict(df_validation)
gbm_accuracy_score = accuracy_score(df_validation_y, gbm_preds)

# Grid search for RandomForestClassifier
rfr_grid_search = GridSearchCV(RandomForestClassifier(random_state=42), rfr_param_grid, cv=5, scoring='accuracy')
rfr_grid_search.fit(df_training, df_training_y)
rfr_best_model = rfr_grid_search.best_estimator_
rfr_preds = rfr_best_model.predict(df_validation)
rfr_accuracy_score = accuracy_score(df_validation_y, rfr_preds)

print(gbm_accuracy_score, rfr_accuracy_score)

In [ ]:
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV


loo = LeaveOneOut()
accuracies = []

df_training_full = df.copy()
df_training_full_y = df_training_full['Survived']
df_training_full.drop(columns=['Survived'], inplace=True)

for train_index, test_index in loo.split(df_training_full):
    X_train, X_test = df_training_full.iloc[train_index], df_training_full.iloc[test_index]
    y_train, y_test = df_training_full_y.iloc[train_index], df_training_full_y.iloc[test_index]
    
    model = gbm_best_model
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracies.append(accuracy_score(y_test, y_pred))

mean_accuracy = np.mean(accuracies)
print(f'Mean accuracy from N-1 CV: {mean_accuracy}')

In [ ]:
# XGBoost
import xgboost as xgb
from sklearn.metrics import accuracy_score

# Initialize the XGBoost classifier. Strategy: play with the parameters or use grid search as above
model = xgb.XGBClassifier(n_estimators=15, random_state=42, max_depth=5, objective='binary:logistic')

# Train the model
model.fit(df_training, df_training_y)

# Make predictions
preds = model.predict(df_validation)

# Evaluate the model
accuracy = accuracy_score(df_validation_y, preds)
print(f'Accuracy: {accuracy}')

In [21]:
# make preds for submission file
model = xgb.XGBClassifier(n_estimators=15, random_state=42, max_depth=5, objective='binary:logistic')
model.fit(df_training, df_training_y)
preds = model.predict(df_test)

In [10]:
# grid search for XGBoost

xgb_param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 5, 10, 20],
    'min_child_weight': [1, 3, 5],  # Equivalent to min_samples_split in XGBoost
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2],
    'reg_alpha': [0, 0.1, 1],
    'reg_lambda': [1, 1.5, 2]
}

# Perform grid search
xgb_grid_search = GridSearchCV(xgb.XGBClassifier(random_state=42), xgb_param_grid, cv=5, scoring='accuracy')
xgb_grid_search.fit(df_training, df_training_y)
xgb_best_model = xgb_grid_search.best_estimator_
xgb_preds = xgb_best_model.predict(df_validation)
xgb_accuracy_score = accuracy_score(df_validation_y, xgb_preds)

print(f'Best Parameters: {xgb_grid_search.best_params_}')
print(f'Validation Accuracy: {xgb_accuracy_score}')

xgboost_best_model = xgb_grid_search.best_estimator_

# N-1 CV
accuracies = []
loo = LeaveOneOut()

df_training_full = df.copy()
df_training_full_y = df_training_full['Survived']
df_training_full.drop(columns=['Survived'], inplace=True)

for train_index, test_index in loo.split(df_training_full):
    X_train, X_test = df_training_full.iloc[train_index], df_training_full.iloc[test_index]
    y_train, y_test = df_training_full_y.iloc[train_index], df_training_full_y.iloc[test_index]
    
    model = xgboost_best_model
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracies.append(accuracy_score(y_test, y_pred))

mean_accuracy = np.mean(accuracies)
print(f'Mean accuracy from N-1 CV: {mean_accuracy}')

In [34]:
import gc
gc.collect()

%reset -f

#### FFN

In [53]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import tensorflow as tf
from keras.optimizers import Adam, SGD
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Dropout, Input

In [60]:
# Enable GPU support for Apple M2
physical_devices = tf.config.list_physical_devices('GPU')
if len(physical_devices) > 0:
    print("GPU is available and enabled.")
else:
    print("GPU is not available.")

# set up n fold cv
n_folds = 5
X = df_training
y = df_training_y

optimizer = Adam()

def create_model(n_inputs):
    model = Sequential()
    model.add(Input(shape=(n_inputs,)))
    model.add(Dense(32, activation='relu'))
    model.add(Dropout(0.1))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)
fold_acc = []
model = create_model(X_train.shape[1])

# train loop
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=0)
    _, accuracy = model.evaluate(X_test, y_test)
    fold_acc.append(accuracy)
    
# evaluate
val_preds = model.predict(df_validation)
val_preds = (val_preds > 0.5).astype(int)
val_accuracy = accuracy_score(df_validation_y, val_preds)

print(f'{n_folds}-fold CV Accuracies: {fold_acc}')
print(f'Validation Accuracy: {round(val_accuracy, 3)}')

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7712 - loss: 0.4339
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7706 - loss: 0.5315
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8324 - loss: 0.4255
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8280 - loss: 0.4293
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8426 - loss: 0.3733
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
5-fold CV Accuracies: [0.7763975262641907, 0.800000011920929, 0.8187500238418579, 0.824999988079071, 0.800000011920929]
Validation Accuracy: 0.767

In [ ]:
# leave one out classification
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()

df_training_full = df.copy()
df_training_full_y = df_training_full['Survived']
df_training_full = df_training_full.drop(columns=['Survived'])

acc = []

for train_index, test_index in loo.split(df_training_full):
    X_train, X_test = df_training_full.iloc[train_index], df_training_full.iloc[test_index]
    y_train, y_test = df_training_full_y.iloc[train_index], df_training_full_y.iloc[test_index]
    
    model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=0)
    preds = model.predict(X_test)
    ac = accuracy_score(y_test, (preds > 0.5).astype(int))
    acc.append(ac)
    
mean_accuracy = np.mean(acc)
print(f'Mean accuracy from N-1 CV: {mean_accuracy}')

In [ ]:
import gc
gc.collect()

%reset -f

#### Support Vector Machine

In [7]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Define a large grid for SVC parameters
grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'degree': [2, 3, 4, 5],  # Only relevant for 'poly' kernel
    'coef0': [0.0, 0.1, 0.5, 1.0],  # Only relevant for 'poly' and 'sigmoid' kernels
}

# Initialize the SVC model
model = SVC()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=5, scoring='accuracy', verbose=0, n_jobs=-1)

# Assuming X_train and y_train are your training data and labels
grid_search.fit(df_training, df_training_y)

# Print the best parameters and best score
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best Score: {grid_search.best_score_}")

model = SVC(**grid_search.best_params_)
preds = model.predict(df_validation)
print(f"Accuracy on validation set: {accuracy_score(df_validation_y, preds)}")

KeyboardInterrupt: